volumes:
  postgres-data:

services:
  
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  next-app:
    build: .
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    env_file:
      - .env
    depends_on:
      - db